import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Footer, Header } from '@/components';
import '../globals.css';
import Provider from '@/providers/provider';
import { ThemeProvider } from 'next-themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({ children, params: { locale } }: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'} suppressHydrationWarning>
      <body className={inter.className}>
        <Header />
        <ThemeProvider
          attribute="class"
          disableTransitionOnChange
        >
          <section className='min-h-[500px]'>
            {children}
          </section>
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}